name: Build Tailwind CSS

on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'
      - 'input.css'
      - 'tailwind.config.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm init -y && npm install tailwindcss

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./input.css -o ./output.css

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Pembaruan otomatis output.css"
          file_pattern: "output.css"
